theme = "base16_transparent"

[editor]
gutters = ["diff"]
lsp.enable = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator = ""

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-base-name", "file-modification-indicator"]
right = ["spacer", "selections", "position"]

[editor.whitespace.render]
space = "none"
nbsp = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"
tabpad = "·"

# For now, I'm binding all my commands to C-x.
[keys.normal."C-x"]
d = ":theme base16_transparent"
l = ":theme catppuccin_latte"

[keys.select."C-x"]
b = ":pipe fribidi --nobreak --nopad"
